### ISSUE TITLE
Multi-touch Interrupt Not Interrupting

### ISSUE THREAD

**Issue by Vacant0mens** [mcauser/micropython-mpr121#3]
Sometimes I feel like a total noob when I'm working on this stuff, but I can't seem to get the interrupt to work properly. I followed the example in examples/irq-multi-touch/irq-multi-touch.py but it doesn't seem to be picking up any touches at all.

I chose Pin(14) for the irq pin, just to make sure I wasn't messing with boot pins or anything (like GPIO16), but I got nothing. 😢 

My handler method is basically copy-pasted from the example (other than changing it to use class properties instead of global variables, and adding some print's and checks to make sure the other parts were working), but I still don't get anything from the irq pin. 

Here's the code I'm using. Any help would be appreciated.
``` python
from machine import I2C, Pin
from time import sleep
import mpr121

class CapacitiveKeys(mpr121.MPR121):
    def __init__(self, address=0x5A, irq=14):
        self._address = address
        self.last = 0
        print("Setting up I2C...")
        self._i2c = I2C(scl=Pin(5), sda=Pin(4))

        if self._i2c.scan().count(address) == 0:
            raise OSError('MPR121 not found at I2C address {:#x}'.format(address))
        
        print("Setting interrupt handler.")
        self.interrupt = Pin(irq, Pin.IN, Pin.PULL_UP) # pin 14 to avoid boot things
        
    def handler(self, pin):
        print("touch detected!")
        bits = self.touched()
        print(bits)
        touched = self.touched()
        diff = self.last ^ touched
        for i in range(12):
            if diff & (1 << i):
                if touched & (1<<i):
                    print('Key {} pressed'.format(i))
                else:
                    print('Key {} released'.format(i))
        self.last = touched    
        self.last_bits = bits


if __name__ == '__main__':
    keys = CapacitiveKeys()
    keys.interrupt.irq(keys.handler, trigger=Pin.IRQ_FALLING)
    print("All set. Waiting for interrupt.")
    while True:
        sleep(10)
        print("waiting for interrupt...")
```

**Comment by mcauser** [comment]
Hey, It's been a few years since I wrote the code...
I can't see anything obvious out of place in your eg. I'm assuming you're using an ESP8266.

Maybe try running the simple irq-multi-touch.py example (and swap the pin numbers).
If that works, your issue might be to do with how the IRQ is triggered or handler is being called inside your class.
If it doesn't work, possibly a hardware/cabling issue. Could try a different IRQ pin (one without any hardware pull-up/pull-downs).

**Comment by Vacant0mens** [comment]
Okay. I copy and pasted the example directly. 
I'm using the Lolin D1 Mini v4, so I had to change line 31 to have `14` instead of `'D3'`, and I un-commented the esp8266 bit on line 13 (and commented line 12).
I added a `while true: sleep(10)` to the end as well, along with `from time import sleep` at the top (so my lines will be 1 off).

And it worked! ... so strange. I'll go through my code again and see what I did different. I thought it was pretty much the same other than abstracting everything into a class, but I guess I'll find out.

**Comment by Vacant0mens** [comment]
oh wow. ... I forgot to init the parent class. 🤦 
I added `super().__init__(i2c=self.i2c, address=address)` to my `__init__()` function and it worked fine.

**Comment by Vacant0mens** [comment]
If I have multiple of these connected to the ESP8266, I basically just connect all the same wires to the same pins (all SDA wires to the SDA pin on the ESP8266, etc) and just make sure the ADDR pin's connection on each one is different, right?

Do I need to have a resistor on the ADDR pin as well? (the datasheet just says "connect ADDR to ..." but I didn't see anything about resistance for the ADDR pin)

**Comment by mcauser** [comment]
You can have 4 of these on the same I2C bus. You can select one of four I2C addresses by connecting the ADDR pin to other pins. You don't need to use resistors to connect to the other pins, connect directly.

Connection | I2C address
-- | --
ADDR -- GND | 0x5A
ADDR -- VCC | 0x5B
ADDR -- SDA | 0x5C
ADDR -- SCL | 0x5D

Most boards have a 100k pull down resistor pulling ADDR to GND. For the default 0x5A address, you can ignore the ADDR pin. If you connect the ADDR pin direct to SDA, it overrides the 100k pull down resistor and uses 0x5C address.

If you want to run more than 4x MPR121s, you'll need an I2C multiplexer, eg.
https://github.com/mcauser/micropython-tca9548a
This lets device lets you have multiple (fixed) I2C address devices on the same bus, and toggle which lanes are open to which device. IRQs would need their own pins if you want to use them for detecting key presses.

**Comment by Vacant0mens** [comment]
Okay. That's kinda what I was thinking. Thanks. 👍
